import express from 'express';
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/streamableHttp.js';
import { z } from 'zod';
import { experimental_generateVideo as generateVideo, experimental_generateImage as generateImage } from 'ai';
import { Agent, setGlobalDispatcher } from 'undici';
import 'dotenv/config';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = join(__dirname, '.env');

const PORT = parseInt(process.env.PORT || '3105', 10);
const OUTPUT_DIR = resolve(process.env.OUTPUT_DIR || join(__dirname, 'output'));

// Extend global fetch timeouts to 15 min for long-running video generation
setGlobalDispatcher(new Agent({
  headersTimeout: 15 * 60 * 1000,
  bodyTimeout: 15 * 60 * 1000,
}));

/* ------------------------------------------------------------------ */
/*  MCP server factory                                                */
/* ------------------------------------------------------------------ */

function createMcpServer() {
  const server = new McpServer({
    name: 'media-generation',
    version: '1.0.0',
  });

  server.tool(
    'generate_video',
    'Generate videos from text prompts, images, or video input using AI models through Vercel AI Gateway.',
    {
      model: z.string().describe('The model to use, e.g., "google/veo-3.1-generate-001", "klingai/kling-v3.0-t2v", "alibaba/wan-v2.6-r2v", "klingai/kling-v2.6-motion-control", "xai/grok-imagine-video"'),
      prompt: z.string().optional().describe('Text description of the video'),
      image: z.string().optional().describe('URL or base64 image for image-to-video or motion-control. For base64, do not include the "data:image/png;base64," prefix.'),
      duration: z.number().optional().describe('Video length in seconds. Supported range varies by model'),
      aspectRatio: z.string().optional().describe('Aspect ratio as "{width}:{height}" (e.g., "16:9", "9:16")'),
      resolution: z.string().optional().describe('Resolution as "{width}x{height}" (e.g., "1920x1080", "1280x720")'),
      providerOptions: z.string().optional().describe('JSON string of provider-specific options. E.g., \'{"vertex":{"generateAudio":true}}\' or \'{"klingai":{"mode":"pro"}}\' or \'{"alibaba":{"referenceUrls":["url1","url2"]}}\''),
      output_path: z.string().optional().describe('Custom output file path. Auto-generated under OUTPUT_DIR if omitted.'),
    },
    async ({ model, prompt, image, duration, aspectRatio, resolution, providerOptions: providerOptionsRaw, output_path }) => {
      try {
        await mkdir(OUTPUT_DIR, { recursive: true });
        const outPath = output_path || join(OUTPUT_DIR, `${randomUUID()}.mp4`);

        if (output_path) {
          await mkdir(dirname(output_path), { recursive: true });
        }

        let finalPrompt;
        if (image) {
          let imageValue = image;
          if (existsSync(image)) {
            const buf = await readFile(image);
            imageValue = buf.toString('base64');
          }
          finalPrompt = { image: imageValue };
          if (prompt) finalPrompt.text = prompt;
        } else {
          finalPrompt = prompt || '';
        }

        const options = {
          model: model,
          prompt: finalPrompt,
        };

        if (duration) options.duration = duration;
        if (aspectRatio) options.aspectRatio = aspectRatio;
        if (resolution) options.resolution = resolution;
        if (providerOptionsRaw) {
          try { options.providerOptions = JSON.parse(providerOptionsRaw); }
          catch { throw new Error('providerOptions must be valid JSON'); }
        }

        const result = await generateVideo(options);

        if (!result.videos || result.videos.length === 0) {
          throw new Error('No video generated by the model.');
        }

        const videoData = result.videos[0].uint8Array;
        await writeFile(outPath, videoData);

        return {
          content: [
            { type: 'text', text: JSON.stringify({ video_path: outPath }, null, 2) },
          ],
        };
      } catch (err) {
        return {
          content: [{ type: 'text', text: `Video generation failed: ${err.message}` }],
          isError: true,
        };
      }
    },
  );

  /* ---- generate_image ---- */

  server.tool(
    'generate_image',
    'Generate images from text prompts using AI models through Vercel AI Gateway. Supports Imagen, Flux, Grok Imagine, and more.',
    {
      model: z.string().describe('The model to use, e.g., "google/imagen-4.0-generate-001", "google/imagen-4.0-ultra-generate-001", "bfl/flux-2-pro", "bfl/flux-kontext-pro", "xai/grok-imagine-image-pro"'),
      prompt: z.string().describe('Text description of the image to generate'),
      n: z.number().optional().describe('Number of images to generate (default: 1)'),
      size: z.string().optional().describe('Image dimensions as "{width}x{height}" (e.g., "1024x1024"). Not supported by xAI models — use aspectRatio instead.'),
      aspectRatio: z.string().optional().describe('Aspect ratio (e.g., "16:9", "1:1", "4:3"). Preferred over size for xAI and Imagen models.'),
      providerOptions: z.string().optional().describe('JSON string of provider-specific options'),
      output_dir: z.string().optional().describe('Directory to save images. Auto-generated under OUTPUT_DIR if omitted.'),
    },
    async ({ model, prompt, n, size, aspectRatio, providerOptions: providerOptionsRaw, output_dir }) => {
      try {
        const imgDir = output_dir || OUTPUT_DIR;
        await mkdir(imgDir, { recursive: true });

        const options = { model, prompt };
        if (n) options.n = n;
        if (size) options.size = size;
        if (aspectRatio) options.aspectRatio = aspectRatio;
        if (providerOptionsRaw) {
          try { options.providerOptions = JSON.parse(providerOptionsRaw); }
          catch { throw new Error('providerOptions must be valid JSON'); }
        }

        const result = await generateImage(options);

        if (!result.images || result.images.length === 0) {
          throw new Error('No images generated by the model.');
        }

        const savedPaths = [];
        for (const image of result.images) {
          const ext = image.mediaType?.split('/')[1] || 'png';
          const filename = `${randomUUID()}.${ext}`;
          const filepath = join(imgDir, filename);
          const buffer = Buffer.from(image.base64, 'base64');
          await writeFile(filepath, buffer);
          savedPaths.push(filepath);
        }

        return {
          content: [
            { type: 'text', text: JSON.stringify({ image_paths: savedPaths }, null, 2) },
          ],
        };
      } catch (err) {
        return {
          content: [{ type: 'text', text: `Image generation failed: ${err.message}` }],
          isError: true,
        };
      }
    },
  );

  return server;
}

/* ------------------------------------------------------------------ */
/*  Express handlers                                                  */
/* ------------------------------------------------------------------ */

async function mcpHandler(req, res) {
  const server = createMcpServer();
  try {
    const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
    res.on('close', () => { transport.close(); server.close(); });
    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  } catch (error) {
    if (!res.headersSent) {
      res.status(500).json({
        jsonrpc: '2.0',
        error: { code: -32603, message: 'Internal server error' },
        id: null,
      });
    }
  }
}

function mcpGetHandler(_req, res) {
  res.status(405).json({
    jsonrpc: '2.0',
    error: { code: -32000, message: 'Method not allowed. Use POST for MCP requests.' },
    id: null,
  });
}

function mcpDeleteHandler(_req, res) {
  res.status(405).json({
    jsonrpc: '2.0',
    error: { code: -32000, message: 'Session termination not supported in stateless mode.' },
    id: null,
  });
}

async function envDebugHandler(_req, res) {
  try {
    const envContents = await readFile(ENV_PATH, 'utf8');
    const envKeys = envContents
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => line.slice(0, line.indexOf('=')).trim());

    const runtimeEnv = envKeys
      .map((key) => `${key}=${process.env[key] ?? ''}`)
      .join('\n');

    res.type('text/plain').send(runtimeEnv);
  } catch (error) {
    res.status(500).type('text/plain').send(`Failed to render runtime env: ${error.message}`);
  }
}

/* ------------------------------------------------------------------ */
/*  App                                                               */
/* ------------------------------------------------------------------ */

const app = express();
app.use(express.json());

app.get('/', envDebugHandler);
app.post('/mcp', mcpHandler);
app.get('/mcp', mcpGetHandler);
app.delete('/mcp', mcpDeleteHandler);

app.get('/health', (_req, res) => res.json({ status: 'ok' }));

app.listen(PORT, () => {
  console.log(`Media Generation MCP server → http://localhost:${PORT}/mcp`);
  console.log(`Output directory: ${OUTPUT_DIR}`);
});
